# Site settings
title: Anne Marieke Doornweerd
email: amdoornweerd@gmail.com
url: https://amdoornweerd.github.io/
description: "Anne Marieke Doornweerd, PhD, is a researcher and science communicator focused on how hormones affect mental health across the female lifespan."
keywords: "female hormones, menstrual cycle, hormonal contraception, mental health, women's health, female health, the pill, IUD, menopause, depression, anxiety, emotions"
skills: "Research Scientist - Science Communicator - Women's Health Expert"
meta_author: Doornweerd AnneMarieke

# Google webmaster tools
google_verify: -1yScNe9CXqY1A0O9sMpgyzoX6sKNbwO0hXt-w_zPr4

# Bing webmaster tools
bing_verify:


# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
#color:
#  primary: 18bc9c #80B3FF
#  primary-rgb: "24,288,156" #"128,179,255"
#  secondary: 2c3e50 #FD6E8A
#  secondary-dark: 233140 #A2122F

color:
  primary: 8e2141           # warm terracotta
  primary-rgb: "191,79,79"
  secondary: f5f0ec         # soft off-white
  secondary-dark: d8cbc3    # muted warm grey

# Footer settings
footer:
  copyright: Dr. AM Doornweerd
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: bluesky
    url: https://web-cdn.bsky.app/profile/did:plc:szolepndeftcbk7fpavfa5t3
  - title: linkedin
    url: https://www.linkedin.com/in/annemariekedoornweerd/
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Amsterdam
  - line: the Netherlands

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /:year/:month/:day/:title/


plugins:
  - jekyll-sitemap
